### ISSUE TITLE
Slack version check fails to show version 4.0

### ISSUE THREAD

**Issue by iancd** [shaquir/ShellScript#1]
Hi @shaquir , I noticed the script was failing to capture the latest version number.  I emailed slack support about this..

```
Hey Ian,

Thanks for reaching out, and apologies for the trouble here.

I'm sorry for the disappointing news, but https://downloads.slack-edge.com/mac_releases/releases.json will soon be removed due to a change in our updating process. Unfortunately there isn't an automatic replacement for it right now. However our Mac folks had a suggestion and I'm going to copy/paste that directly for you:

They can hit our update endpoint, that URL looks something like:
https://slack.com/desktop/update?id=<any-random-string>&platform=darwin&os_version=<their-os-version>&app_version=<their-app-version>&channel=<their-channel>

They can find an example in their browser.log. Search for a line with the text MacUpdater: Direct feed URL and copy the URL from there.

I hope this helps. If you have any further questions around this, please don't hesitate to let me know.

Kindly,
Dee
```

**Comment by shaquir** [comment]
Hi @iancd,
I appreciate you bringing this to my attention and providing their feedback!  
I would presume the easiest fix would be changing:
`currentSlackVersion="4.0.0"`
But, I will look into automatically pulling the latest version number from the new website that they provided.
With Sincere Thanks,
Shaq

**Comment by shaquir** [comment]
Hi @iancd 
I have updated the code to check https://slack.com/downloads/mac for the version number.  I have no idea how to hit the update endpoint link that they provided.  I'll keep looking for better ways to check the Version.
Thanks again for the find.

`currentSlackVersion=$(/usr/bin/curl -s 'https://slack.com/downloads/mac' | grep -o "Version [0-9]\.[0-9]\.[0-9]" | cut -d' ' -f2 )`

**Comment by iancd** [comment]
@shaquir 
The current version check is behind again.  Slack support have advised to use the RSS feed as it's always updated unlike the webpage. Shows latest version 4.0.1

```
currentSlackVersion=$(/usr/bin/curl -sL 'https://slack.com/release-notes/mac/rss' | grep -o "Slack-[0-9]\.[0-9]\.[0-9]"  | cut -c 7-11 | head -n 1)
```
However I can't download the links included in the RSS.

**Comment by shaquir** [comment]
Hi @iancd,
Thank you for all your help so far!
I'm glad Slack finally provided us with this RSS feed (Hopefully it stays up).
I also get a "AccessDenied" error from the linked "https://downloads.slack-edge.com/mac_releases/Slack-4.0.1.dmg" RSS link, so I'll keep the download link pointed to https://slack.com/ssb/download-osx .
Best Regards,
Shaq
