### ISSUE TITLE
Slack version check does not work via international redirect

### ISSUE THREAD

**Issue by iancd** [shaquir/ShellScript#2]
Hi again @shaquir. Thanks for making a speedy fix, unfortunately this doesn't work if curl is used outside the US where international language redirects are operating.
Actual result ""
Expected result "4.0.0"

https://slack.com/downloads/mac redirected to https://slack.com/intl/en-gb/downloads/mac

There's a simple fix for the code by making curl follow redirects `usr/bin/curl -sL`
Thanks for your efforts - this script is very useful.

**Comment by shaquir** [comment]
Added!  Great find.

**Comment by iancd** [comment]
Spot on
