### ISSUE TITLE
cp command does not preserve icon resources

### ISSUE THREAD

**Issue by iancd** [shaquir/ShellScript#3]
Hi @shaquir
I found the copy command on line 53 *does not* copy the icon resources properly from the Slack DMG disk image. It's possible other resources are not preserved.

![Slack](https://user-images.githubusercontent.com/27893345/62121934-8535c480-b2bc-11e9-8a3e-93e846697bca.png)
 
In my tests in macOS 10.14.6 with Slack 4.0.0, changing this command to ditto fully replicated a Finder copy and preserved the icon resources. 

```
ditto -rsrc /Volumes/Slack*/Slack.app /Applications/Slack.app
```

**Comment by shaquir** [comment]
Great find as always @iancd !
